/**
 * GENERATED by scripts/extract-dsh.mjs — do not edit by hand.
 * Extracted from official deepseek-ai/deepseek-harness @ 47f943859
 * (see docs/dsh-minimal-audit.md for verification).
 */
export const DSH_MINIMAL_SYSTEM_PROMPT = "You are a helpful software engineer assistant.";

export const DSH_BASH_DESCRIPTION = "Run commands in a bash shell\n* When invoking this tool, the contents of the \"command\" parameter does NOT need to be XML-escaped.\n* You don't have access to the internet via this tool.\n* You do have access to a mirror of common linux and python packages via apt and pip.\n* State is persistent across command calls and discussions with the user.\n* To inspect a particular line range of a file, e.g. lines 10-25, try 'sed -n 10,25p /path/to/the/file'.\n* Please avoid commands that may produce a very large amount of output.\n* Please run long lived commands in the background, e.g. 'sleep 10 &' or start a server in the background.";

export const DSH_EDITOR_DESCRIPTION = "Custom editing tool for viewing, creating and editing files\n* State is persistent across command calls and discussions with the user\n* If `path` is a file, `view` displays the result of applying `cat -n`. If `path` is a directory, `view` lists non-hidden files and directories up to 2 levels deep\n* The `create` command cannot be used if the specified `path` already exists as a file\n* If a `command` generates a long output, it will be truncated and marked with `<response clipped>`\n\nNotes for using the `str_replace` command:\n* The `old_str` parameter should match EXACTLY one or more consecutive lines from the original file. Be mindful of whitespaces!\n* If the `old_str` parameter is not unique in the file, the replacement will not be performed. Make sure to include enough context in `old_str` to make it unique\n* The `new_str` parameter should contain the edited lines that should replace the `old_str`";

export const DSH_TRUNCATED_MESSAGE = "<response clipped><NOTE>To save on context only part of this file has been shown to you. You should retry this tool after you have searched inside the file with `grep -n` in order to find the line numbers of what you are looking for.</NOTE>";

export const DSH_LOST_PREFIX_MESSAGE = "<response clipped><NOTE>The beginning of this command output was dropped by the terminal scrollback limit. The following text is the earliest retained output.</NOTE>\\n";

export const DSH_SHELL_RESET_MESSAGE = "The persistent bash shell was reset; the next bash call starts from the workspace with a fresh current directory and environment.";

export const DSH_EDITOR_TRUNCATED_MESSAGE = "<response clipped><NOTE>To save on context only part of this file has been shown to you. You should retry this tool after you have searched inside the file with `grep -n` in order to find the line numbers of what you are looking for.</NOTE>";

export const DSH_BASH_TIMEOUT_MS = 300000;
export const DSH_MAX_OUTPUT_CHARS = 16000;

export const DSH_MINIMAL_TOOLS = [
  {
    "name": "bash",
    "description": "Run commands in a bash shell\n* When invoking this tool, the contents of the \"command\" parameter does NOT need to be XML-escaped.\n* You don't have access to the internet via this tool.\n* You do have access to a mirror of common linux and python packages via apt and pip.\n* State is persistent across command calls and discussions with the user.\n* To inspect a particular line range of a file, e.g. lines 10-25, try 'sed -n 10,25p /path/to/the/file'.\n* Please avoid commands that may produce a very large amount of output.\n* Please run long lived commands in the background, e.g. 'sleep 10 &' or start a server in the background.",
    "parameters": {
      "type": "object",
      "properties": {
        "command": {
          "type": "string",
          "description": "The bash command to run. Relative path is preferred in the command."
        }
      },
      "required": [
        "command"
      ]
    }
  },
  {
    "name": "str_replace_editor",
    "description": "Custom editing tool for viewing, creating and editing files\n* State is persistent across command calls and discussions with the user\n* If `path` is a file, `view` displays the result of applying `cat -n`. If `path` is a directory, `view` lists non-hidden files and directories up to 2 levels deep\n* The `create` command cannot be used if the specified `path` already exists as a file\n* If a `command` generates a long output, it will be truncated and marked with `<response clipped>`\n\nNotes for using the `str_replace` command:\n* The `old_str` parameter should match EXACTLY one or more consecutive lines from the original file. Be mindful of whitespaces!\n* If the `old_str` parameter is not unique in the file, the replacement will not be performed. Make sure to include enough context in `old_str` to make it unique\n* The `new_str` parameter should contain the edited lines that should replace the `old_str`",
    "parameters": {
      "type": "object",
      "properties": {
        "command": {
          "type": "string",
          "enum": [
            "view",
            "create",
            "str_replace",
            "insert"
          ],
          "description": "The commands to run. Allowed options are: `view`, `create`, `str_replace`, `insert`."
        },
        "path": {
          "type": "string",
          "description": "Absolute path to file or directory, e.g. `/repo/file.py` or `/repo`."
        },
        "file_text": {
          "type": "string",
          "description": "Required parameter of `create` command, with the content of the file to be created."
        },
        "insert_line": {
          "type": "integer",
          "description": "Required parameter of `insert` command. The `new_str` will be inserted AFTER the line `insert_line` of `path`."
        },
        "new_str": {
          "type": "string",
          "description": "Optional parameter of `str_replace` command containing the new string (if not given, no string will be added). Required parameter of `insert` command containing the string to insert."
        },
        "old_str": {
          "type": "string",
          "description": "Required parameter of `str_replace` command containing the string in `path` to replace."
        },
        "view_range": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Optional parameter of `view` command when `path` points to a file. If none is given, the full file is shown. If provided, the file will be shown in the indicated line number range, e.g. [11, 12] will show lines 11 and 12. Indexing at 1 to start. Setting `[start_line, -1]` shows all lines from `start_line` to the end of the file."
        }
      },
      "required": [
        "command",
        "path"
      ]
    }
  }
];

export const DSH_MINIMAL_TOOLS_SHA256 = "067b681bbdf9ddbc976ab754db76468807473f3d0fd6ed3dd7fd8bacddab777d";
